apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tinkoff-trading-bot.fullname" . }}-config
  namespace: {{ include "tinkoff-trading-bot.namespace" . }}
  labels:
    {{- include "tinkoff-trading-bot.labels" . | nindent 4 }}
data:
  SANDBOX: {{ .Values.env.SANDBOX | quote }}
  I_KNOW_WHAT_I_AM_DOING: {{ .Values.env.I_KNOW_WHAT_I_AM_DOING | quote }}
  UI_ENABLED: {{ .Values.env.UI_ENABLED | quote }}
  UI_HOST: {{ .Values.env.UI_HOST | quote }}
  UI_PORT: {{ .Values.env.UI_PORT | quote }}
  PYTHONPATH: {{ .Values.env.PYTHONPATH | quote }}
  AUTO_START: {{ .Values.env.AUTO_START | quote }}
  instruments_config.json: |
{{- .Values.instrumentsConfig | toJson | indent 4 }}
