{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "tinkoff-trading-bot.namespace" . }}
  labels:
    {{- include "tinkoff-trading-bot.labels" . | nindent 4 }}
{{- end }}
