apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tinkoff-trading-bot.fullname" . }}-secrets
  namespace: {{ include "tinkoff-trading-bot.namespace" . }}
  labels:
    {{- include "tinkoff-trading-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  TOKEN: {{ .Values.secrets.TOKEN | quote }}
  ACCOUNT_ID: {{ .Values.secrets.ACCOUNT_ID | quote }}
