apiVersion: v1
kind: Secret
metadata:
  name: tinkoff-bot-secrets
  namespace: tinkoff-bot
type: Opaque
stringData:
  # Required
  TOKEN: "REPLACE_ME"
  # Optional (if empty, bot uses first account)
  ACCOUNT_ID: ""

