apiVersion: v1
kind: Service
metadata:
  name: tinkoff-bot-ui
  namespace: tinkoff-bot
spec:
  selector:
    app: tinkoff-bot
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP

